name: Transforms Jupyter Notebooks to Rmarkdown
on:
  workflow_dispatch:

jobs:
  transformer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: pip install jupytext
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello Matti"
